 route:
     receiver: 'slack'

 receivers:
     - name: 'slack'
       slack_configs:
       - send_resolved: true
         username: 'thabet'
         channel: '#prom-alerts'
         api_url: 'https://hooks.slack.com/services/XXXXXXXXXXX'
         icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
         title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
         text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
